global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  external_labels:
      monitor: 'perf-test'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
         - targets: ['cadvisor:8080']

  - job_name: 'fluent-bit'
    metrics_path: /api/v1/metrics/prometheus
    static_configs:
         - targets: ['fluent-bit:2020']
